### PR TITLE
update to sdk v3

### PR DESCRIPTION
**Pull request by AviAvni**

### CODE REVIEW

**Comment by AviAvni** [comment]
@7sharp9 @dsyme I updated the sdk to the latest manualy and now this repository work as expected
I'm waiting that the sdk v3 is pushed to nuget

**Comment by dsyme** [comment]
@AviAvni That's great, though note that the TP SDK version doesn't yet properly support cross-targeting generative providers - that's TBD, so you'll need another update after this

**Comment by AviAvni** [comment]
@dsyme I updated to latest sdk but I get this errors
image

**Comment by dsyme** [comment]
@AviAvni Thanks, I'll look into the failures.  (I also pushed some more fixes to the TPSDK if you want to give it a go yourself, though I'm not sure it fixes this problem)

**Comment by 7sharp9** [comment]
@AviAvni Im not actively working on this but feel free to keep using this as a repo to solve the many issues with TP's :-)

**Comment by dsyme** [comment]
@AviAvni The latest TPSDK now supports context-based generative providers, if you would now like to update this

**Pull request merged**
